// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfPgTLjgR0JXCxm3k0Rgbn1ou8BgL8v3Y',
    appId: '1:76150197392:web:b425648fd43e017bc7dc15',
    messagingSenderId: '76150197392',
    projectId: 'fifth-6289c',
    authDomain: 'fifth-6289c.firebaseapp.com',
    storageBucket: 'fifth-6289c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbPToD50YD9O1Xuo8F2KAlw25db625PqE',
    appId: '1:76150197392:android:ca3d1ebcd9357ce2c7dc15',
    messagingSenderId: '76150197392',
    projectId: 'fifth-6289c',
    storageBucket: 'fifth-6289c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnrt6wFgK0JxvGIjoOc9gV8tPsezV_sAk',
    appId: '1:76150197392:ios:ac8c04b043c85b91c7dc15',
    messagingSenderId: '76150197392',
    projectId: 'fifth-6289c',
    storageBucket: 'fifth-6289c.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication5',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnrt6wFgK0JxvGIjoOc9gV8tPsezV_sAk',
    appId: '1:76150197392:ios:ac8c04b043c85b91c7dc15',
    messagingSenderId: '76150197392',
    projectId: 'fifth-6289c',
    storageBucket: 'fifth-6289c.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication5',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfPgTLjgR0JXCxm3k0Rgbn1ou8BgL8v3Y',
    appId: '1:76150197392:web:06a60121ccb72125c7dc15',
    messagingSenderId: '76150197392',
    projectId: 'fifth-6289c',
    authDomain: 'fifth-6289c.firebaseapp.com',
    storageBucket: 'fifth-6289c.firebasestorage.app',
  );

}